spring.application.name=medientApi

spring.datasource.url=jdbc:mysql://localhost:3306/medient
spring.datasource.username=root
spring.datasource.password=1111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=org.medient.dto

spring.config.import=optional:application-secret.properties
spring.profiles.active=secret

openapi.easy-drug-url=https://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList