spring.application.name=medientApi

spring.datasource.url=jdbc:log4jdbc:mysql://localhost:3306/medient
spring.datasource.username=root
spring.datasource.password=1111
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=org.medient.dto

spring.config.import=application-secret.properties
openapi.easy-drug-url=https://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList